#!/usr/bin/env python

import os
import os.path

def generateShfile():
    dirname = os.path.abspath('./')
    o = open('grompp.sh', 'w')
    o.write("#!/bin/bash\n")
    o.write("#PBS -l nodes=1:ppn=8\n")
    o.write("cd $PBS_O_WORKDIR\n")

    sample =['pre', 'a1', 'a2', 'a3']
    for i in sample:
        #gromacs 3.3
        #o.write("/share/apps/gromacs333n/bin/grompp_mpi -np 8 -f run.mdp -c run.gro -p *.top -o equil\n")
        #o.write("/opt/openmpi/bin/mpirun -np 8 /share/apps/gromacs333n/bin/mdrun_mpi -s equil -c run\n")
        #gromacs 4.0
        o.write("grompp -f run.mdp -c run.gro -p *.top -o equil -maxwarn 2\n")
        o.write("mpirun -np 8 mdrun -s equil -c run\n")
        o.write("mkdir %s/%s\n"%(dirname,i))
        o.write("cp * %s/%s\n"%(dirname,i))
        o.write("rm \#*\n")
        o.write("rm *.tpr grompp.sh.*\n")
    


if __name__ == "__main__":
    generateShfile()
    os.system('qsub grompp.sh')
