#!/usr/bin/env python
import os
import os.path
import sys

usage = """this
"""

cmd = ""
try:
    len(sys.argv) < 2
except:
    print usage

cmd = " ".join([i for i in sys.argv[1:]])
allpath = [i for i in os.listdir(".")]
allpath.sort()
for i in allpath:
    if os.path.isdir(i):
        os.chdir(i)
        os.system(cmd)
        os.chdir("../")

