# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.34
#
# Don't modify this file, modify the SWIG interface instead.

package FSearch;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package FSearchc;
bootstrap FSearch;
package FSearch;
@EXPORT = qw(setResidual getResidual );

# ---------- BASE METHODS -------------

package FSearch;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package FSearch;

*setResidual = *FSearchc::setResidual;
*getResidual = *FSearchc::getResidual;

# ------- VARIABLE STUBS --------

package FSearch;

1;
