# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.34
#
# Don't modify this file, modify the SWIG interface instead.

package Fsearch;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package Fsearchc;
bootstrap Fsearch;
package Fsearch;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package Fsearch;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Fsearch;

*setResidual = *Fsearchc::setResidual;
*getResidual = *Fsearchc::getResidual;

# ------- VARIABLE STUBS --------

package Fsearch;

1;
