#!/usr/bin/env python
#This code is used to handle multi directionary operation

import sys
import os
import os.path

def getAction():
    list = []
    counter = 0
    for i in sys.argv:
        if counter > 0:
            list.append(i)
        counter += 1
    action = ' '.join("%s"%temp for temp in list)
    return action

def operation(a):
    os.system(a)

def multi_operate(a):
    f = os.listdir("./")
    for i in f:
        if os.path.isdir(i):
            os.chdir(i)
            operation(a)
            os.chdir("../") 

if __name__ == '__main__':
    sys_action = getAction()
    multi_operate(sys_action)   


