#!/usr/bin/env python
import os
import os.path
import sys
import argparse

def usage():
    print """Operate all of the sub folders.
"""


def get_folders():
    dlist = []
    cmd = " ".join([i for i in sys.argv[1:]])
    for i in os.listdir("./"):
        if os.path.exists(i) and os.path.isdir(i):
            dlist.append(i)

    dlist.sort()
    return dlist


def exec_folders(dlist, cmd, args):
    ignore_folders = []
    if args.ignore:
        ignore_folders = args.ignore
    for i in dlist:
        if i not in ignore_folders:
            run = cmd
            os.chdir(i)
            if args.v:
                print "cmd processing in %s"%os.getcwd()
            if args.arg:
                folder = os.path.basename(os.getcwd())
                print folder
                run = run.replace("xx", folder)
            if args.v:
                print "cmd is %s"%run
            os.system(run)
            os.chdir("..")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("cmd", default="", nargs="*", help="command line to execute")
    parser.add_argument("-R", action="store_true", help="reverse the folder sequence")
    parser.add_argument("-v", action="store_true", help="verbose output")
    parser.add_argument("-arg", action="store_true", help="take folder as argument")
    parser.add_argument("-ignore", nargs="*", help="ignore the following folders")
    #parser.add_argument("-a", nargs=3, type=int,help="get the angle of a1-a2-a3")
    args = parser.parse_args()

    cmd = args.cmd
    cmd = " ".join(cmd)

    if args.v:
        print "CMD: ", cmd

    dlist = get_folders()
    if args.R:
        dlist.sort(reverse=True)
    if args.ignore:
        ignore_folders = args.ignore

    if len(cmd.strip()) > 0:
        exec_folders(dlist, cmd, args)

if __name__ == "__main__":
    main()
