#!/usr/bin/env python
import os
import os.path
import sys

usage = """Operate all of the sub folders.
"""

cmd = ""
try:
    len(sys.argv) < 2
except:
    print usage

dlist = []
cmd = " ".join([i for i in sys.argv[1:]])
for i in os.listdir("./"):
    if os.path.exists(i) and os.path.isdir(i):
        dlist.append(i)

dlist.sort()

"""
for i in dlist:
    os.chdir(i)
    print "cmd processing in %s"%os.getcwd()
    os.system(cmd)
    os.chdir("..")

"""

for i in range(len(dlist)):
    n = len(dlist) - 1 - i
    os.chdir(dlist[n])
    print "cmd processing in %s"%os.getcwd()
    os.system(cmd)
    os.chdir("..")
    
