#!/usr/bin/env python
"""
Usage: html2mobi [link]
"""

import os
import sys
import time
DEBUG = 0

if len(sys.argv) > 1:
    link = sys.argv[1]
    fname = "k%d"%(int(time.time()))

    cmd = "pandoc -s -r html %s -t epub -s -o %s.epub"%(link, fname)
    if DEBUG:
        print cmd
    os.system(cmd)
    cmd = "pandoc -s -r html %s -t docx -s -o %s.docx"%(link, fname)
    if DEBUG:
        print cmd
    os.system(cmd)
    cmd = "kindlegen %s.epub -o %s.mobi"%(fname, fname)
    if DEBUG:
        print cmd
    os.system(cmd)
else:
    print __doc__



