#!/usr/bin/env python
"""
Usage: html2mobi [link]
Log:
2016-11-07: output the log info
"""

import os
import sys
import time
DEBUG = 0

if len(sys.argv) > 1:
    link = sys.argv[1]
    fname = "k%d"%(int(time.time()))

    o = open(fname+".log", "w")
    o.write("%s\n"%link)
    o.write("convert html to epub\n")
    cmd = "pandoc -s -r html %s -t epub -s -o %s.epub"%(link, fname)
    o.write("done\n")
    if DEBUG:
        print cmd
    os.system(cmd)
    o.write("convert html to docx\n")
    cmd = "pandoc -s -r html %s -t docx -s -o %s.docx"%(link, fname)
    o.write("done\n")
    o.write("convert html to docx\n")
    cmd = "pandoc -s -r html %s -t latex --latex-engine=xelatex -s -o %s.pdf"%(link, fname)
    o.write("done\n")
    if DEBUG:
        print cmd
    os.system(cmd)
    o.write("convert epub to mobi\n")
    cmd = "kindlegen %s.epub -o %s.mobi"%(fname, fname)
    o.write("done\n")
    if DEBUG:
        print cmd
    os.system(cmd)
    o.write("remove epub file\n")
    cmd = "rm %s.epub"%fname
    os.system(cmd)
    o.write("done\n")
    o.close()
else:
    print __doc__



