#!/usr/bin/env python

import time
import sys

time_start = time.time()
time_limit = float(sys.argv[1])*3600

while(1):
    time_now = time.time()
    dt = time_now - time_start
    if dt > time_limit:
        break

print time_limit

