#!/usr/bin/env python

"""
Convert any file format (with correct ext) to .gen.
@Note: need ase.
any2gen infile
"""

import sys
from ase.io import read, write

if len(sys.argv) > 1:
    infile = sys.argv[1]
    atoms = read(infile)
    write("geo_start.gen", atoms)
else:
    print(__doc__)

