#!/usr/bin/env python

import sys
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.surface import Slab, SlabGenerator, generate_all_slabs, Structure, Lattice, ReconstructionGenerator
from pymatgen.io.vasp.inputs import Poscar

if len(sys.argv) > 1:
    fname = sys.argv[1]
    struct = Structure.from_file(fname)
    struct = SpacegroupAnalyzer(struct).get_conventional_standard_structure()
    open('conventional.vasp', 'w').write(str(Poscar(struct)))

