#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print "warning no job to delete"
    else:
        start = int(sys.argv[1])
        end = int(sys.argv[2]) + 1
        for i in range(start, end):
            os.system('qdel %d'%i)
            print "job %d is being killed"%i
