#!/usr/bin/env python

import sys, os, shutil

if len(sys.argv) > 1:
    atoms = [int(i) for i in sys.argv[1:]]

    f = open("POSCAR", "r")
    lines = f.readlines()
    f.close()

    flag = 1
    n = 0
    fname = ''
    while(flag):
        flag = 0
        fname = "POSCAR.%03d"%n
        if os.path.exists(fname):
            flag = 1
        n += 1
    shutil.copy("POSCAR", fname)

    for i in range(len(lines)):
        lines[i] = lines[i].replace("F", "T")
    
    # print lines[7]
    na0 = 8
    for i in atoms:
        lines[na0+i] = lines[na0+i].replace("T", "F")

    o = open("POSCAR", "w")
    for i in lines:
        o.write(i)
    o.close()
        
    

    
