#!/usr/bin/env python

import os
import sys
import shutil

if not os.path.exists("inp"):
    os.mkdir("inp")

if os.path.exists("POSCAR"):
    shutil.copy("POSCAR", "inp")
if os.path.exists("POTCAR"):
    shutil.copy("POTCAR", "inp")
if os.path.exists("KPOINTS"):
    shutil.copy("KPOINTS", "inp")
if os.path.exists("INCAR"):
    shutil.copy("INCAR", "inp")
if os.path.exists("run.in"):
    shutil.copy("run.in", "inp")
if os.path.exists("ICONST"):
    shutil.copy("ICONST", "inp")

