BIOGRF 200
DESCRP Title Card Required
REMARK generated by simulation python
HETATM     1 N                   0.00000   0.00000  -1.19843    N   0 0  0.00000
HETATM     2 N                   0.00000   0.00000  -0.07214    N   0 0  0.00000
HETATM     3 O                   0.00000   0.00000   1.11174    O   0 0  0.00000
END

