"""
parse the bonds.reax generated by Lammps
@ here: we only assume one step stored in the file
"""

from operator import attrgetter

class ReaxBond():
    def __init__(self, ):
        self.id = 0
        self.type = 0
        self.nbonds = 0
        self.bonded_atoms = []
        self.bond_orders = []
        self.bo = 0.0 # total bond order
        self.lp = 0.0
        self.q = 0.0

class BondsTable():
    def __init__(self, filename="bonds.reax"):
        self.bonds = []
        self.read(filename)
    def read(self, filename):
        f = open(filename, "r")
        for i in f:
            tokens = i.strip().split()
            if not i.strip().startswith("#"):
                bond = ReaxBond()
                bond.id = int(tokens[0])
                bond.bo = float(tokens[-3])
                bond.q = float(tokens[-1])
                self.bonds.append(bond)
        # sort
        self.bonds = sorted(self.bonds, key=attrgetter('id'))

def test():
    a = BondsTable("/net/hulk/home6/chengtao/PUREMD/mmo2/em/bonds.reax")
    for i in a.bonds:
        #pass
        print i.id

if __name__ == "__main__":
    test()
    

