#!/usr/bin/env python
import os

def parsefolder(folder, filetype):
    for i in os.listdir(folder):
        fullname = os.path.join(folder, i)
        if os.path.isdir(fullname):
            parsefolder(fullname, filetype)
        else:
            if filetype in fullname:
                os.remove(fullname)

if __name__ == "__main__":
    parsefolder('.',".edr")
    parsefolder('.',".tpr")
    parsefolder('.',".trr")
    parsefolder('.',".sh.")
    parsefolder('.',"test.pdb")
