#!/usr/bin/env python

import os
o = open('all.sh', 'w')
o.write("""#!/bin/bash
#PBS -l nodes=1:ppn=8
cd $PBS_O_WORKDIR
""")

folderList = []

for i in os.listdir('.'):
    if os.path.isdir(i):
        folderList.append(i)

folderList.sort()

for i in folderList:
    o.write('cd %s\n'%i)
    o.write('grompp -f equil -c em -p *.top -o equil -maxwarn 2\n')
    o.write('mdrun -s equil -c equil\n')
    o.write('cd ..\n')

o.close()
